### ISSUE TITLE
따로 커뮤니티가 없어서 여기에 질문을 남깁니다.

### ISSUE THREAD

**Issue by sgim74528** [samchon/framework#5]
안녕하세요.
만드신 프레임워크에 관심이 있는 사람입니다.

아프리카tv, 다음팟tv, 카카오tv, 팝콘tv 등의 서비스를 구축한다고 쳤을때
보통 udp 프로토콜로 영상/음성을 송수신 하게 되는데 당연히 분산처리 시스템이 필요합니다.

제가 생각하고 있는 분산처리 시스템은 BJ(방송을 송출하는 자)가 마스터 스트리밍 서버에 udp 데이터를 보내면
슬레이브 스트리밍 서버에 자동으로 리플리케이션이 되고 수요(방송을 시청하는 자)에 맞게 리플리케이션의 정도를 가변적으로 변하게 하려고 합니다.

그 후 클라이언트는 최적의 스트리밍 서버를 찾아서 BJ의 UDP 데이터를 수신하게 되겠죠.

여기서 질문이 있습니다.

보통 위 시스템을 구축하려면 low level 부터 코드를 다 짜야 하는데 삼촌 프레임워크를 이 서비스에 접목 한다면 적합할지가 궁금합니다.

수고스럽게 정리하신 삼촌 프레임워크의 레퍼런스를 보고 있는데 딱 이렇다 할 결론이 내려지지 않아 질문을 드리게 되었습니다.

개발자님 화이팅 하십시요!

**Comment by samchon** [comment]
죄송합니다. 삼촌 프레임워크는 TCP 프토콜을 사용하고 있으며, 네트워크 메시지 또한 XML 의 형태를 띄고 있기에, 말씀하신 상황에 적합하지 않습니다.

**Comment by sgim74528** [comment]
아하!
따른 답변 고맙습니다.

죄송하실 필요는 없으십니다!
