### ISSUE TITLE
std 컨테이너를 상속하는것은 메모리 릭을 유발합니다.

### ISSUE THREAD

**Issue by ArtBlnd** [samchon/framework#7]
virtual 소멸자를 가지고있지 않는 std 컨테이너는 오브젝트가 소멸할 시에 소멸자가 호출되지 않습니다.
중요한 메모리 릭을 유발합니다.

**Comment by ArtBlnd** [comment]
std 컨테이너는 원레 상속하시면 안 됩니다... ㅠㅠㅠ
소멸자가 호출되지 않는 이유는 소멸자가 virtual이 아니라서
vptr형식으로 소멸자의 포인터가 남지 않기 때문에
상속을 해버리면 상속된 소멸자만 호출되기 때문입니다...

**Comment by GoodGoodJM** [comment]
해당 이슈에 대해 제가 전에 이슈를 올린적이 있었는데요, 해당 링크를 걸어드리겠습니다.
https://github.com/samchon/framework/issues/4

**Comment by GoodGoodJM** [comment]
상위 클래스 래퍼에 대해 delete를 했을때는 virtual이 아니므로 하위 클래스의 소멸자가 호출되지 않지만, 해당 클래스(하위 클래스)의 래퍼에 대해 delete를 하시면 상위 클래스의 소멸자도 호출될 겁니다. 때문에 다형성을 이용해 래퍼를 쥐고있는게 아닌이상 큰 문제는 없을거 같습니다.

**Comment by samchon** [comment]
저는 STL 상속 건에 대해서, 수퍼타입을 통해 소멸자를 호출하는 게 아닌 한 문제 없다고 알고 있습니다.

그리하여 아래 코드와 같이 서브타입에 대한 소멸자 호출 코드를 돌렸을 때는, 문제가 없었습니다.

```cpp
#include <iostream>
#include <vector>
using namespace std;

// SOMETHING TO BE DELETED
class Something
{
private:
    int val;
    
public:
    Something()
    {
        this->val = -1;
    };
    Something(int val)
    {
        this->val = val;
    };
    ~Something()
    { // BELOW MESSAGE IS PRINTED, THEN NO PROBLEM
        cout << this->val << " has deleted" << endl;
    };
};

// EXTENDS VECTOR AND TEST WHETHER THE 
// Something OBJECTS ARE CORRECTLY DELETED
template <typename T>
class MyVector : public vector<T>
{
private:
    typedef vector<T> super;

public:
    using super::super;
};

// DO TEST
void test()
{
    MyVector<Something> v;
    v.emplace_back(3);
    v.emplace_back(4);
    v.emplace_back(5);
}

int main()
{
    test();
    return 0;
}
```

**Comment by ArtBlnd** [comment]
vector 안의 소멸자는 호출되지 않는걸로 압니다.

**Comment by ArtBlnd** [comment]
@GoodGoodJM 

vector 자체의 타입으로 delete를 해 주었을 경우에는 그럼 기존에 있던 소멸자는 호출되지 않습니다만...
newtype : public vector
일때 vector type으로 delete를 해 주었을 경우에는 vector에 있는 소멸자만 호출이 되고.
newtype type 으로 delete를 해 주었을 경우에는 newtype에 있는 소멸자만 호출되는걸로 압니다.

**Comment by ArtBlnd** [comment]
에초에 std 컨테이너를 상속하는건 좋은 행위가 아닙니다.

**Comment by ArtBlnd** [comment]
처음부터 위험한 부분을 남겨놓는것보다는 전부 다시 리팩토링해서 안전하게 수정하는게 낫다고 생각합니다. 또한 에초에 std 컨테이너를 상속할 필요성이 있는지 조차 사실 잘 모르겠네요.

**Comment by GoodGoodJM** [comment]
@ArtBlnd 하위클래스의 래퍼로 delete를 하면 해당 하위클래스의 소멸자와 상위 클래스의 소멸자는 호출이됩니다. 저 또한 STL의 컨테이너를 상속받는 것에 대해 부정적이고, 권장하지 않는다고 배워 거부감이 있었지만, 해당 라이브러리 개발자께서 의도한 바가 있다면 경고 정도의 주석을 달아주고 쓰는데는 무리 없다고 생각합니다.

**Comment by GoodGoodJM** [comment]
저 역시 다형성을 이용하지 않는다면 굳이 상속시킬 필요 없이 Wrapper클래스를 만들어서 사용하는 것이 낫다고 생각하나, 이는 개발자님이 개인적으로 생각해두신 유즈케이스가 있을 것 이라고 생각합니다.
