### ISSUE TITLE
Outdated Examples in the WIKI

### ISSUE THREAD

**Issue by cloudcalvin** [samchon/framework#8]
Hello,

I am a new user and am interested in generating XML using your library.

When running the third example in the XML tutorial which is on both the WIKI and in the github pages, as well as on NPM(https://www.npmjs.com/package/samchon-xml) I get the following error: 

"[ts] Property 'insertValue' does not exist on type 'XML'."

I dont see it in the API so I am wondering if it has been replaced by another command?

**Comment by samchon** [comment]
Thanks for your reporting. I've forgotten to add the `insertValue` method.

I will realize it after get off from my duty.

**Comment by samchon** [comment]
https://github.com/samchon/framework/blob/master/ts/src/samchon/library/xml/XML.ts#L477-L492

XML.insertValue() has implemented.
